accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.ColumnListView.as_view(), name="column-list"),
    path("feed/", views.ColumnFeedView.as_view(), name="feed"),
    path(
        "moderator/posts/",
        views.ModeratorPostListView.as_view(),
        name="moderator-post-list",
    ),
    path(
        "moderator/posts/<pk>/mark-as-public/",
        views.ModeratorMarkAsPublic.as_view(),
        name="mark-as-public",
    ),
    path("posts/<pk>/", views.PostDetailView.as_view(), name="post-detail"),
    path(
        "columns/<pk>/", views.ColumnDetailView.as_view(), name="column-detail"
    ),
    path(
        "create/column/",
        views.ColumnCreateView.as_view(),
        name="column-create",
    ),
    path("create/post/", views.PostCreateView.as_view(), name="post-create"),
]

home/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django_otp.admin import OTPAdminSite


urlpatterns = [
    path('api-auth/', include('rest_framework.urls')),
    path('accounts/', include('allauth.urls')),
    path('auth/', include('djoser.urls')),
    path('secret-admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='columns'))
    # re_path(r'^.*', TemplateView.as_view(template_name='index.html')),
]

if not settings.DEBUG:
    admin.site.__class__ = OTPAdminSite
admin.site.site_title = "Django Security Tutorial"
admin.site.site_header = "Django Security Tutorial"

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from .managers import UserManager


class User(AbstractUser):

    email = models.EmailField(unique=True, max_length=255)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    # option 1
    # e.g Staff, Client, Manager, etc.
    # user_type = models.CharField(max_length=100)

    # # option 2
    # is_client = models.BooleanField(default=True)
    # is_manager = models.BooleanField(default=False)

    objects = UserManager()

    def __str__(self):
        return self.email


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # fields, properties, user types
    user_type = models.CharField(max_length=100, choices=(
        ("Reader", "Reader"),
        ("Writer", "Writer"),
        ("Coordinator", "Coordinator"),
        ("Moderator", "Moderator")
    ), default='Reader')

    def __str__(self):
        return self.user.email


class Column(models.Model):
    coordinator = models.ForeignKey(User, on_delete=models.CASCADE)
    writers = models.ManyToManyField(
        User, related_name='writers_columns')
    moderators = models.ManyToManyField(
        User, related_name='moderators_columns')

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    column = models.ForeignKey(Column, on_delete=models.CASCADE)
    writer = models.ForeignKey(
        User, related_name='posts', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    public = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Subscription(models.Model):
    """This is the link between a user and a column that
    they're subscribed to"""
    reader = models.ForeignKey(
        User, related_name='user_subscriptions', on_delete=models.CASCADE)
    column = models.ForeignKey(
        Column, related_name='column_subscriptions', on_delete=models.CASCADE)

    def __str__(self):
        return self.reader.email


def post_save_user_receiver(sender, instance, created, *args, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


post_save.connect(post_save_user_receiver, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Column, Post

User = get_user_model()


class PostForm(forms.ModelForm):
    column = forms.ModelChoiceField(queryset=Column.objects.none())

    class Meta:
        model = Post
        fields = ['title', 'column']

    def __init__(self, *args, **kwargs):
        self.user_id = kwargs.pop('user_id')
        super().__init__(*args, **kwargs)
        user = User.objects.get(id=self.user_id)
        self.fields['column'].queryset = user.writers_columns.all()

    def clean(self):
        user = User.objects.get(id=self.user_id)
        data = self.cleaned_data
        column = data.get('column', None)
        if not column:
            raise forms.ValidationError("Please select a column")

        if column not in user.writers_columns.all():
            raise forms.ValidationError(
                "Please select a column you can write for")


class ColumnForm(forms.ModelForm):
    writers = forms.ModelMultipleChoiceField(
        queryset=User.objects.filter(userprofile__user_type='Writer'))
    moderators = forms.ModelMultipleChoiceField(
        queryset=User.objects.filter(userprofile__user_type='Moderator'))

    class Meta:
        model = Column
        fields = [
            'writers',
            'moderators',
            'name',
        ]

    def clean(self):
        data = self.cleaned_data

        writers = data.get('writers', None)
        moderators = data.get('moderators', None)

        if writers is None:
            raise forms.ValidationError("Please select a writer")

        if moderators is None:
            raise forms.ValidationError("Please select a moderator")

        writers_check = writers.filter(userprofile__user_type='Writer')
        if writers_check.count() != writers.count():
            raise forms.ValidationError(
                "Please ensure all the users are valid writers")

        moderators_check = moderators.filter(
            userprofile__user_type='Moderator')
        if moderators_check.count() != moderators.count():
            raise forms.ValidationError(
                "Please ensure all the users are valid writers")


class SubscribeForm(forms.Form):
    hidden = forms.HiddenInput()

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import reverse, redirect, get_object_or_404
from .models import Column, Post, Subscription
from .forms import ColumnForm, PostForm, SubscribeForm
from .mixins import (
    ValidCoordinatorMixin, ValidWriterMixin, ValidModeratorMixin,
    ModeratorHasAccessMixin
)


class ColumnListView(generic.ListView):
    model = Column
    template_name = 'accounts/column_list.html'


class ColumnDetailView(generic.FormView):
    form_class = SubscribeForm
    template_name = 'accounts/column_detail.html'

    def get_success_url(self):
        return reverse("accounts:column-detail", kwargs={
            'pk': self.kwargs['pk']
        })

    def form_valid(self, form):
        if not self.request.user.userprofile.user_type == 'Reader':
            # message notification saying they cant subscribe
            return redirect(reverse("accounts:column-detail", kwargs={
                'pk': self.kwargs['pk']
            }))
        column = get_object_or_404(Column, id=self.kwargs['pk'])
        Subscription.objects.get_or_create(
            reader=self.request.user,
            column=column
        )
        return super(ColumnDetailView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ColumnDetailView, self).get_context_data(**kwargs)
        column = Column.objects.get(id=self.kwargs['pk'])
        context['subscribed'] = False
        try:
            Subscription.objects.get(
                reader=self.request.user,
                column=column
            )
            context['subscribed'] = True
        except Subscription.DoesNotExist:
            pass
        context.update({
            "object": column
        })
        return context


class ColumnCreateView(LoginRequiredMixin, ValidCoordinatorMixin, generic.CreateView):
    model = Column
    form_class = ColumnForm
    template_name = 'accounts/column_create.html'

    def get_success_url(self):
        return reverse("columns:column-list")

    def form_valid(self, form):
        column = form.save(commit=False)
        column.coordinator = self.request.user
        column.save()
        return super(ColumnCreateView, self).form_valid(form)


class PostCreateView(LoginRequiredMixin, ValidWriterMixin, generic.CreateView):
    model = Post
    form_class = PostForm
    template_name = 'accounts/post_create.html'

    def get_success_url(self):
        return reverse("columns:column-list")

    def get_form_kwargs(self):
        kwargs = super(PostCreateView, self).get_form_kwargs()
        kwargs.update({
            "user_id": self.request.user.id
        })
        return kwargs

    def form_valid(self, form):
        post = form.save(commit=False)
        post.writer = self.request.user
        post.save()
        return super(PostCreateView, self).form_valid(form)


class ModeratorPostListView(LoginRequiredMixin, ValidModeratorMixin, generic.ListView):
    template_name = 'accounts/moderator_post_list.html'

    def get_queryset(self):
        columns = list(
            self.request.user.moderators_columns.values_list('id', flat=True))
        qs = Post.objects.filter(column__id__in=columns)
        return qs


class PostDetailView(LoginRequiredMixin, generic.DetailView):
    model = Post
    template_name = 'accounts/post_detail.html'


class ModeratorMarkAsPublic(LoginRequiredMixin, ValidModeratorMixin, ModeratorHasAccessMixin, generic.View):
    def get(self, request, *args, **kwargs):
        post = Post.objects.get(id=kwargs['pk'])
        post.public = True
        post.save()
        return redirect(reverse("accounts:post-detail", kwargs={'pk': kwargs['pk']}))


class ColumnFeedView(LoginRequiredMixin, generic.ListView):
    template_name = 'accounts/feed.html'

    def get_queryset(self):
        # return Subscription.objects.filter(reader=self.request.user)
        return self.request.user.user_subscriptions.all()

accounts/templates/accounts/column_create.html
{% extends "base.html" %}

{% block content %}

<h1>Column Create</h1>
<a href="{% url 'columns:column-list' %}">Back to all columns</a>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Submit</button>
</form>

{% endblock content %}

accounts/templates/accounts/column_detail.html
{% extends "base.html" %}

{% block content %}

<h1>Column: {{ object.name }}</h1>
<a href="{% url 'columns:column-list' %}">Back to all columns</a>

    {% if not request.user.userprofile.user_type == 'Reader' %}

    <h4>Coordinator: {{ column.coordinator.email }}</h4>
    <hr />

    <h4>Writers</h4>
    {% for writer in column.writers.all %}
        <p>{{ writer.email }}</p>
    {% endfor %}
    <hr />

    <h4>Moderators</h4>
    {% for moderator in column.moderators.all %}
        <p>{{ moderator.email }}</p>
    {% endfor %}

    <hr />

    {% endif %}

    {% if request.user.userprofile.user_type == 'Reader' %}
        {% if not subscribed %}
        <form method="POST">
            {% csrf_token %}
            <button type="submit">Subscribe to this column</button>
        </form>
        {% else %}
        <p>You are subscribed</p>
        {% endif %}
    {% endif %}

    <h4>Posts</h4>
    {% for post in column.post_set.all %}
        <a href="{% url 'accounts:post-detail' post.id %}">{{ post.title }}</a>
    {% endfor %}

{% endblock content %}

accounts/templates/accounts/column_list.html
{% extends "base.html" %}

{% block content %}

<h1>Column list</h1>
<a href="{% url 'columns:column-create' %}">Create a column</a>
<hr />
{% for column in object_list %}
    <a href="{% url 'columns:column-detail' column.id %}">{{ column.name }}</a>
    <br />
{% endfor %}

{% endblock content %}

accounts/templates/accounts/feed.html
{% extends "base.html" %}

{% block content %}

<h1>My Feed</h1>
<hr />
{% for subscription in object_list %}
    <a href="{% url 'columns:column-detail' subscription.column.id %}">
    {{ subscription.column.name }}
    </a>
    <br />
{% endfor %}

{% endblock content %}

accounts/templates/accounts/moderator_post_list.html
{% extends "base.html" %}

{% block content %}

<h1>Moderators Post list</h1>
<hr />
{% for post in object_list %}
    <a href="{% url 'post-detail' post.id %}">{{ post.title }}</a>
    <br />
{% endfor %}

{% endblock content %}

accounts/templates/accounts/post_create.html
{% extends "base.html" %}

{% block content %}

<h1>Post Create</h1>
<a href="{% url 'columns:column-list' %}">Back to all posts</a>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Submit</button>
</form>

{% endblock content %}

accounts/templates/accounts/post_detail.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'columns:column-detail' object.column.id %}">Back to all posts</a>

    <h4>Writer: {{ object.writer.email }}</h4>
    <hr />

    {{ object.title }}

{% if request.user.userprofile.user_type == 'Moderator' %}
    {% if not object.public %}
    <a href="{% url 'accounts:mark-as-public' object.id %}">Mark as public</a>
    {% else %}
    <p>This post is public</p>
    {% endif %}
{% endif %}

{% endblock content %}