accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.ColumnListView.as_view(), name="column-list"),
    path("feed/", views.ColumnFeedView.as_view(), name="feed"),
    path(
        "moderator/posts/",
        views.ModeratorPostListView.as_view(),
        name="moderator-post-list",
    ),
    path(
        "moderator/posts/<pk>/mark-as-public/",
        views.ModeratorMarkAsPublic.as_view(),
        name="mark-as-public",
    ),
    path("posts/<pk>/", views.PostDetailView.as_view(), name="post-detail"),
    path(
        "columns/<pk>/", views.ColumnDetailView.as_view(), name="column-detail"
    ),
    path(
        "create/column/",
        views.ColumnCreateView.as_view(),
        name="column-create",
    ),
    path("create/post/", views.PostCreateView.as_view(), name="post-create"),
]

home/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django_otp.admin import OTPAdminSite


urlpatterns = [
    path('api-auth/', include('rest_framework.urls')),
    path('accounts/', include('allauth.urls')),
    path('auth/', include('djoser.urls')),
    path('secret-admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='columns'))
    # re_path(r'^.*', TemplateView.as_view(template_name='index.html')),
]

if not settings.DEBUG:
    admin.site.__class__ = OTPAdminSite
admin.site.site_title = "Django Security Tutorial"
admin.site.site_header = "Django Security Tutorial"

templates/base.html
My user: {{ request.user.email }}

{% if request.user.is_authenticated %}
{% if request.user.userprofile.user_type == 'Reader' %}
    <a href="{% url 'accounts:feed' %}">My feed</a>
{% endif %}
<a href="{% url 'account_logout' %}">Logout</a>
{% else %}
<a href="{% url 'account_login' %}">Login</a>
{% endif %}
<br />
{% block content %}

{% endblock content %}

templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    Hello world
    <a href="/session/348329482/">go to payment</a>
    <form method="POST">
        {%csrf_token%}
        <button type="submit">Submit</button>
    </form>
</body>

</html>